# Generated by Django 4.2.7 on 2023-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nin',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
