# Generated by Django 4.2.7 on 2023-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Feale')], max_length=50, null=True),
        ),
    ]
